ngrm.ngadmin.cloudinary.index:
    path: /ngrm/dashboard
    defaults:
        _controller: "netgen_remote_media.controller.ngadmin:index"

ngrm.ngadmin.cloudinary.library:
    path: /ngrm/library
    defaults:
        _controller: "netgen_remote_media.controller.ngadmin:library"

ngrm.ngadmin.cloudinary.library.load_more:
    path: /ngrm/library/more
    defaults:
        _controller: "netgen_remote_media.controller.ngadmin:loadMore"
        methods: [POST]

ngrm.ngadmin.cloudinary.multiupload:
    path: /ngrm/multiupload
    defaults:
        _controller: "netgen_remote_media.controller.ngadmin:uploadAndGenerate"

ngrm.ngadmin.cloudinary.upload_summary:
    path: /ngrm/multiupload/summary
    defaults:
        _controller: "netgen_remote_media.controller.ngadmin:uploadSummary"
