parameters:
    #netgen_remote_media.default.cloudinary.folder_name: ''
    netgen_remote_media.cloudinary.delete_not_used: true

services:
    netgen_remote_media.handler_registry:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Transformation\Registry

    netgen_remote_media.variation.resolver:
        alias: netgen_remote_media.variation.resolver.siteaccess

    netgen_remote_media.variation.resolver.default:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\VariationResolver\VariationResolver
        arguments:
            - "@ezpublish.config.resolver"
            - "%ezpublish.siteaccess.list%"
        #lazy: true
        #calls:
            #- [setVariations, ["$image_variations;netgen_remote_media$"]]

    netgen_remote_media.variation.resolver.siteaccess:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\VariationResolver\SiteAccessAwareVariationResolver
        lazy: true
        calls:
            - [setVariations, ["$image_variations;netgen_remote_media$"]]

    netgen_remote_media.provider.cloudinary.gateway:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\Gateway\CloudinaryApiGateway
        calls:
            - [initCloudinary, ['%netgen_remote_media.parameters.cloudinary.account_name%', '%netgen_remote_media.parameters.cloudinary.account_key%', "%netgen_remote_media.parameters.cloudinary.account_secret%"]]

    netgen_remote_media.provider.cloudinary:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\CloudinaryProvider
        arguments:
            - "@netgen_remote_media.handler_registry"
            - "@netgen_remote_media.variation.resolver"
            - "@netgen_remote_media.provider.cloudinary.gateway"
            - "@?logger"

    netgen_remote_media.helper:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Helper
        arguments:
            - "@netgen_remote_media.provider"
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.content_type"
