parameters:
    netgen_remote_media.cloudinary.delete_not_used: true

services:
    netgen_remote_media.handler_registry:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Transformation\Registry

    netgen_remote_media.variation.resolver:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\VariationResolver
        lazy: true
        calls:
            - [setVariations, ["$image_variations;netgen_remote_media$"]]

    netgen_remote_media.provider.cloudinary.gateway:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\Gateway\CloudinaryApiGateway
        calls:
            - [initCloudinary, ['%netgen_remote_media.parameters.cloudinary.account_name%', '%netgen_remote_media.parameters.cloudinary.account_key%', "%netgen_remote_media.parameters.cloudinary.account_secret%"]]

    netgen_remote_media.provider.cloudinary.gateway.cached:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\Gateway\CachedGateway
        arguments:
            - "@netgen_remote_media.provider.cloudinary.gateway"
            - "@ezpublish.cache_pool"

    netgen_remote_media.provider.cloudinary:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\CloudinaryProvider
        arguments:
            - "@netgen_remote_media.handler_registry"
            - "@netgen_remote_media.variation.resolver"
            - "@netgen_remote_media.provider.cloudinary.gateway.cached"
            - "@?logger"

    netgen_remote_media.helper:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Helper
        arguments:
            - "@netgen_remote_media.provider"
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.content_type"

    # content browser specifics
    netgen_remote_media.ngadminui.menu_plugin.ngremotemedia:
        class: Netgen\Bundle\RemoteMediaBundle\MenuPlugin\RemoteMediaMenuPlugin
        tags:
            - { name: "netgen_admin_ui.menu_plugin" }

    netgen_remote_media.provider.cloudinary.admin:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\ContentBrowser\AdminProvider
        parent: netgen_remote_media.provider.cloudinary

    netgen_remote_media.content_browser.backend.cloudinary:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\ContentBrowser\Backend\CloudinaryBackend
        arguments:
            - "@netgen_remote_media.provider.cloudinary.admin"
        tags:
            -  { name: netgen_content_browser.backend, item_type: cloudinary }
