services:
    netgen_remote_media.cache.cache_wrapper:
        class: Netgen\Bundle\RemoteMediaBundle\Cache\CacheWrapper
        arguments:
            - "@ezpublish.cache_pool"

    netgen_remote_media.provider.cloudinary.gateway.cached:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\Gateway\Cache\StashCachedGateway
        arguments:
            - "@netgen_remote_media.provider.cloudinary.gateway"
            - "@netgen_remote_media.cache.cache_wrapper"
            - "%netgen_remote_media.cloudinary.cache_ttl%"
