services:
    netgen_remote_media.templating.twig.extension:
        class: Netgen\Bundle\RemoteMediaBundle\Templating\Twig\Extension\NetgenRemoteMediaExtension
        arguments:
            - "@netgen_remote_media.provider"
            - "@ezpublish.translation_helper"
            - "@ezpublish.api.service.content_type"
            - "@netgen_remote_media.helper"
            - "@netgen_remote_media.variation.resolver"
        tags:
            - { name: twig.extension }
